### ISSUE TITLE
Error executing lua .../.vim/plugged/orgmode.nvim/lua/orgmode/org/syntax.lua:20: Vim(syntax):E399: Not enough  arguments

### ISSUE THREAD

**Issue by XVilka** [kristijanhusak/orgmode.nvim#133] opened 2021-11-03 06:37 UTC
### Are you using "tree-sitter" branch?

No

### Describe the bug

```
Error executing vim.schedule lua callback: ...v/.vim/plugged/orgmode.nvim/lua/orgmode/parser/files.lua:230: Vim(lua):E5108: Error executing lua ...kov/.vim/plugged/orgmode.nvim/lua/orgmode/org/syntax.lua:20: Vim(syntax):E399: Not enough
 arguments: syntax region orgmodeBlockSrcrust :tangle selector.rs :noweb tangle matchgroup=comment start="^\s*#+BEGIN_SRC\ rust :tangle selector.rs :noweb tangle\s*$" end="^\s*#+END_SRC\s*$" keepend contains=@orgmodeBlockSrcrust :tangle
 selector.rs :noweb tangle,org_block_delimiter
 ```

### Steps to reproduce

Open file https://github.com/XVilka/roper2/blob/master/src/evo/selector.org

### Expected behavior

No error

### OS / Distro

Fedora Linux 35

### Neovim version/commit

0.5.1

**Comment by kristijanhusak** [comment] 2021-11-05 08:55
This is duplicate of https://github.com/kristijanhusak/orgmode.nvim/issues/90.

**Closed by kristijanhusak** 2021-11-05 08:55 UTC
Labels: bug
