### ISSUE TITLE
Filetags

### ISSUE THREAD

**Issue by jghauser** [kristijanhusak/orgmode.nvim#25] opened 2021-07-04 16:42 UTC
**Describe the bug**
Filetags aren't very functional. I found the following issues:
- They don't autocomplete (in my case, using compe). Neither can I autocomplete them when I write filetags, nor will filetags show up as options when I write normal tags.
- When opening the agenda while matching for a tag, tasks which should have inherited a tag from a filetag will not show up.

**To Reproduce**

1. Write a filetag, no suggestions will show up

and

1. Write a filetag
2. Add a normal tag and press tab to complete
3. Filetag will not show up

and

1. Add a filetag to a file with a TODO entry
2. Open agenda and match for tag
4. TODO entry will not show up

**Expected behavior**
Filetags should be inherited and applied just like other tags

**Emacs functionality**
I have never used emacs orgmode, and I don't know how the functionality is there.

**System information:**
 - OS: Arch
 - Neovim version: latest 0.5 release

**Comment by kristijanhusak** [comment] 2021-07-04 20:39
Completion within the `#+FILETAG` is not implemented. We can move that to separate issue.

Regarding everything else, I cannot reproduce it.

Can you give me some basic content of your org file and how you define filetag?

Here's the working gif:

![filetags](https://user-images.githubusercontent.com/1782860/124398929-a0b37080-dd18-11eb-8fd1-fffcda4992b6.gif)

**Comment by jghauser** [comment] 2021-07-04 20:46
I put the tags in colons like this: `#+FILETAGS: :Peter:Boss:Secret:`.

I got the syntax [from here](https://orgmode.org/manual/Tag-Inheritance.html).

**Comment by kristijanhusak** [comment] 2021-07-04 21:03
For some unknown reason I thought filetags as comma separated. Will fix it, thanks.

**Comment by kristijanhusak** [comment] 2021-07-04 21:53
This should be fixed now. Let me know if it works.

**Closed** 2021-07-04 21:53 UTC
Labels: bug

**Comment by jghauser** [comment] 2021-07-05 18:46
It works! Thanks a lot for the super quick fix :)
